### PR TITLE
Update go-swagger to latest upstream v0.19.0.

### PR DESCRIPTION
**Pull request by firejump**
Used actively maintained go-bindata fork from github.com/kevinburke/go-bindata
to regenerate bindata.go.
Removed WithContext flag which has been deprecated, see https://github.com/go-swagger/go-swagger/issues/1684 for context.

### CODE REVIEW

**Comment by firejump** [comment]
On second thought, I probably didn't have to regenerate bindata.go as part of this update; let me know if you'd like me to remove this from the PR.

**Comment by mikkeloscar** [comment]
Thanks!

I'm fine with including the bindata.go change, but please also update the README to point to the go-bindata fork

**Comment by firejump** [comment]
> I'm fine with including the bindata.go change, but please also update the README to point to the go-bindata fork
Sure, done.

**Comment by firejump** [comment]
Thanks!

**Pull request merged**
