### PR TITLE
feat(model): add `binding: "required"` when required

### PR DESCRIPTION
**Pull request by Devil-MayCry**
when swagger model parms is required, add `binding: "required"` , instead of removeing "omitempty"

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Hi, it looks like you are updating go-swagger. But do it correctly you need to use dep instead of just updating the files checked into the `vendor/` folder.

Please also link the upstream change in go-swagger which fixes this problem, because it's not clear from this.

Thanks!

**Comment by Devil-MayCry** [comment]
https://github.com/Devil-MayCry/go-swagger/commit/9bfa8f0f42e002e10a1040eee49b1b09bb46967b

This is what I update in go-swagger and bindata.go file update

**Comment by Devil-MayCry** [comment]
The binding: "required" is not json property , not gin, so update bindata.go is only way I can figure out to solve the problem. The other way is give up using go-swagger gen-model code, it's impossible obviously

**Comment by mikkeloscar** [comment]
Thanks, now I understand.

However I don't understand what problem it solves to use the gin validation logic, since models are already being validated by go-swagger. What exactly does using `binding: "required"` solve? And example would be really helpful for me to understand.

Thanks for your time!

**Comment by Devil-MayCry** [comment]
well，go-swagger can solve validation by readRequest. But you use BindJSON already, why not throwing the error just here?
It just my opinion, I just believe we should use gin's feature more, haha

**Comment by mikkeloscar** [comment]
I understand but go-swagger does more than just validate that the field has a value or not, it also validates that the content is valid e.g. if it has to match a certain regex pattern.

I would not mind using a different implementation which could do the same as what go-swagger does, but since this won't add any additional feature I think the burden of maintaining a custom go-swagger fork, is higher than just continuing to use go-swagger and not all the features of gin.

I hope you understand, and I really do appreciate you taking the time on this.

**Comment by Devil-MayCry** [comment]
You are right, I understand. Thanks your time

**Pull request closed without merging**
